apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: mytopic
  namespace: {{ .Values.configurationOverrides.global.namespace }}
spec:
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
    retention.ms: "100000"