apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: mytopic
  namespace: {{ .Values.configurationOverrides.global.namespace }}
spec:
  replicas: 3
  partitionCount: 12
  configs:
    cleanup.policy: "delete"
    retention.ms: "100000"